### ISSUE TITLE
How I can Contributing?

### ISSUE THREAD

**Issue by kszere** [chalkboardspace/chalkboard#1]
Where is source code?

**Comment by cjpatoilo** [comment]
@kszere I'm very happy to see you animated to contribute.
If you want to help you could track all bugs that you find and report it here.

Now, the source code of the Chalkboard platform still no available. 
Before open, I need to remove the hard code and fix somethings.

**Comment by cjpatoilo** [comment]
Now, I will close this issue and I will wait for your contribution.
Thank you @kszere
